"""
gen_notebook.py  --  Generates mpdocvqa_e2e.ipynb
Run from the mpdocvqa_benchmark/ directory:
    python gen_notebook.py

MP-DocVQA specifics vs MMLongBench:
  - Data: imdb_val.npy (numpy) instead of JSON
  - No PDF download: 64,057 OCR + image files already local
  - Parsing: mpdocvqa_parser.py (Textract OCR) instead of MinerU
  - Evidence: answer_page_idx (single int) instead of evidence_pages list
  - Gold: valid_answers (list, multi-annotator) instead of single string
  - Primary metric: ANLS (DocVQA standard)
  - 100% answerable: no unanswerable questions in MP-DocVQA val set
"""
import json, pathlib, uuid

def cell_id():
    return uuid.uuid4().hex[:8]

def md(source):
    return {"cell_type": "markdown", "id": cell_id(), "metadata": {}, "source": source}

def code(source):
    return {
        "cell_type": "code", "execution_count": None,
        "id": cell_id(), "metadata": {}, "outputs": [],
        "source": source,
    }

cells = []

# ── Phase 0 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "# GraMM-RAG -- MP-DocVQA End-to-End Implementation\n"
    "\n"
    "**Single-benchmark pilot notebook** for the dissertation.  \n"
    "Dataset: MP-DocVQA (val split) -- 5,187 QA records, 927 unique documents, avg 37 pages/doc.  \n"
    "Data already local: 64,057 Textract OCR JSON files + 64,057 page images.  \n"
    "Primary metric: **ANLS** (Average Normalised Levenshtein Similarity -- DocVQA standard).\n"
    "\n"
    "| Phase | Description |\n"
    "|---|---|\n"
    "| 0 | Setup & configuration |\n"
    "| 1 | Load & filter data (pilot: 100 questions) |\n"
    "| 1.5 | Exploratory data analysis -- corpus stats, charts, tables |\n"
    "| 2 | Verify OCR + image file coverage for pilot documents |\n"
    "| 3 | Parse docs with mpdocvqa_parser (Textract OCR) + temporal annotation |\n"
    "| 4 | Compute embeddings (E5-Mistral text) + build PyG graphs |\n"
    "| 5 | Train HGT with evidence-guided InfoNCE loss |\n"
    "| 6 | Train query router (DeBERTa-v3-base) |\n"
    "| 7 | Tune reward function (alpha, beta, lambda, tau grid search) |\n"
    "| 8 | Flat-vector RAG baseline (FAISS + LLM) |\n"
    "| 9 | GraMM-RAG full evaluation (3 seeds) |\n"
    "| 10 | Results comparison table |\n"
    "\n"
    "**To extend to the full run:** change `N_PILOT = None` in Phase 0 and re-run."
))

cells.append(code(
    "# ═══════════════════════════════════════════════════════════════════════════\n"
    "# PHASE 0 -- Setup & Configuration\n"
    "# ═══════════════════════════════════════════════════════════════════════════\n"
    "\n"
    "# --- PILOT FILTER: change ONLY this line to extend to the full run ---------\n"
    "N_PILOT = None     # <- set 100 for pilot run\n"
    "# ---------------------------------------------------------------------------\n"
    "\n"
    "SEED    = 42\n"
    "\n"
    "HGT_EPOCHS    = 5  if N_PILOT else 50   # <- EXTEND: 50 for full run\n"
    "ROUTER_EPOCHS = 1  if N_PILOT else 3    # <- EXTEND: 3 for full run\n"
    "# Pilot: skip heavy embedding on CPU (loads ~1.3 GB E5 model; too slow for pilot).\n"
    "# Full run on GPU: set SKIP_EMBEDDING = False so embeddings are computed.\n"
    "SKIP_EMBEDDING  = bool(N_PILOT)             # <- EXTEND: set False for full GPU run\n"
    "# Pilot: cap pages embedded per doc (only used when SKIP_EMBEDDING=False).\n"
    "MAX_PAGES_PILOT = 15 if N_PILOT else None  # <- EXTEND: None for full run\n"
    "\n"
    "import sys, pathlib\n"
    "ROOT = pathlib.Path('.').resolve()          # flat repo root (src/ alongside notebook)\n"
    "sys.path.insert(0, str(ROOT))\n"
    "\n"
    "DATA_DIR   = ROOT / 'data'        / 'mpdocvqa'\n"
    "OCR_DIR    = DATA_DIR / 'ocr'\n"
    "IMG_DIR    = DATA_DIR / 'images'\n"
    "IMDB_DIR   = DATA_DIR / 'imdbs'\n"
    "PARSED_DIR = ROOT / 'parsed'     / 'mpdocvqa'\n"
    "EMB_DIR    = ROOT / 'embeddings' / 'mpdocvqa'\n"
    "GRAPH_DIR  = ROOT / 'graphs'     / 'mpdocvqa'\n"
    "MODEL_DIR  = ROOT / 'results' / 'models'\n"
    "RESULTS_DIR = ROOT / 'results'\n"
    "\n"
    "# --- Fallback path variables (defined early so later phases never NameError)\n"
    "hgt_save_path   = MODEL_DIR / 'hgt_mpdocvqa'    / 'best_model.pt'\n"
    "reward_save     = MODEL_DIR / 'reward_mpdocvqa.json'\n"
    "router_save_dir = MODEL_DIR / 'router_mpdocvqa' / 'best_model'\n"
    "vector_out_path = RESULTS_DIR / 'baseline_vector_mpdocvqa_pilot.json'\n"
    "faiss_indices   = {}       # populated in Phase 8\n"
    "gramm_results   = {}       # populated in Phase 9\n"
    "pilot_doc_ids   = []       # populated in Phase 1\n"
    "\n"
    "print(f'ROOT: {ROOT}')\n"
    "print(f'N_PILOT = {N_PILOT}  (set None for full 5,187-question run)')"
))

cells.append(code(
    "import json, random, re, logging, os\n"
    "from pathlib import Path\n"
    "from collections import Counter, defaultdict\n"
    "import numpy as np\n"
    "import torch\n"
    "\n"
    "logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')\n"
    "logger = logging.getLogger('mpdocvqa_e2e')\n"
    "\n"
    "DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
    "print(f'Device: {DEVICE}')\n"
    "if DEVICE == 'cuda':\n"
    "    print(f'  GPU: {torch.cuda.get_device_name(0)}')\n"
    "    print(f'  VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\n"
    "\n"
    "# Load API keys from .env (mpdocvqa_benchmark/.env, then project root .env)\n"
    "try:\n"
    "    from dotenv import load_dotenv\n"
    "    _loaded = load_dotenv(dotenv_path=pathlib.Path('.env'), override=False)\n"
    "    if not _loaded:\n"
    "        load_dotenv(dotenv_path=ROOT / '.env', override=False)\n"
    "    print('API keys loaded from .env')\n"
    "except ImportError:\n"
    "    print('python-dotenv not installed -- reading keys from shell environment only')\n"
    "\n"
    "if not os.environ.get('TOGETHER_API_KEY') or os.environ.get('TOGETHER_API_KEY','').startswith('your-'):\n"
    "    print('Warning: TOGETHER_API_KEY not set -- generation will use extractive fallback')\n"
    "    os.environ.pop('TOGETHER_API_KEY', None)\n"
    "if not os.environ.get('OPENAI_API_KEY') or os.environ.get('OPENAI_API_KEY','').startswith('your-'):\n"
    "    print('Warning: OPENAI_API_KEY not set -- KG triplets will be empty (safe to proceed)')\n"
    "    os.environ.pop('OPENAI_API_KEY', None)"
))

cells.append(code(
    "for d in [DATA_DIR, OCR_DIR, IMG_DIR, PARSED_DIR, EMB_DIR, GRAPH_DIR,\n"
    "          MODEL_DIR / 'hgt_mpdocvqa',\n"
    "          MODEL_DIR / 'router_mpdocvqa',\n"
    "          RESULTS_DIR / 'figures']:\n"
    "    d.mkdir(parents=True, exist_ok=True)\n"
    "print('All directories ready.')"
))

# ── Phase 1 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 1 -- Load & Filter Data\n"
    "\n"
    "Load the MP-DocVQA val split from `imdbs/imdb_val.npy` (numpy format).  \n"
    "Each record contains: `question`, `valid_answers`, `image_name` (page filenames),\n"
    "`pages` (context window page indices), `answer_page_idx` (which page in `pages` holds the answer),\n"
    "`total_doc_pages` (full document length).  \n"
    "\n"
    "Derived fields added:\n"
    "- `doc_id`: prefix of `image_name[0]` before `_pN`\n"
    "- `_actual_answer_page`: `pages[answer_page_idx]` (0-indexed absolute page number)\n"
    "- `_q_words`, `_a_words`: word counts for EDA"
))

cells.append(code(
    "imdb = np.load(str(IMDB_DIR / 'imdb_val.npy'), allow_pickle=True)\n"
    "# imdb[0] is metadata header; QA records start at index 1\n"
    "\n"
    "def extract_doc_id(image_name):\n"
    "    \"\"\"Strip _pN suffix from image name to get doc_id.\"\"\"\n"
    "    m = re.match(r'^(.+)_p(\\d+)$', str(image_name))\n"
    "    return m.group(1) if m else str(image_name)\n"
    "\n"
    "all_questions = []\n"
    "for rec in imdb[1:]:\n"
    "    img_names  = list(rec.get('image_name', []))\n"
    "    pages_list = list(rec.get('pages', []))\n"
    "    ans_idx    = int(rec.get('answer_page_idx', 0))\n"
    "    total_pgs  = int(rec.get('total_doc_pages', 1))\n"
    "\n"
    "    doc_id = extract_doc_id(img_names[0]) if img_names else ''\n"
    "    actual_ans_page = pages_list[ans_idx] if ans_idx < len(pages_list) else 0\n"
    "\n"
    "    valid_ans = list(rec.get('valid_answers', rec.get('answers', [])))\n"
    "    valid_ans = [str(a) for a in valid_ans if a]\n"
    "    primary_ans = valid_ans[0] if valid_ans else ''\n"
    "\n"
    "    all_questions.append({\n"
    "        'question_id':        int(rec.get('question_id', 0)),\n"
    "        'question':           str(rec.get('question', '')),\n"
    "        'answers':            valid_ans,      # list (multi-annotator)\n"
    "        'doc_id':             doc_id,\n"
    "        'image_names':        img_names,\n"
    "        'pages':              pages_list,\n"
    "        'answer_page_idx':    ans_idx,\n"
    "        'total_doc_pages':    total_pgs,\n"
    "        '_actual_answer_page': actual_ans_page,\n"
    "        '_q_words':           len(str(rec.get('question', '')).split()),\n"
    "        '_a_words':           len(primary_ans.split()),\n"
    "        '_unanswerable':      False,          # MP-DocVQA has no unanswerable Qs\n"
    "        # evidence_pages for router training: actual answer page\n"
    "        '_evidence_pages':    [actual_ans_page],\n"
    "        '_evidence_sources':  ['text'],        # all MP-DocVQA content is text\n"
    "    })\n"
    "\n"
    "random.seed(SEED)\n"
    "pilot_questions = random.sample(all_questions, N_PILOT) if N_PILOT else all_questions\n"
    "pilot_doc_ids   = sorted({q['doc_id'] for q in pilot_questions})\n"
    "\n"
    "print(f'Total QA records  : {len(all_questions):,}')\n"
    "print(f'Pilot questions   : {len(pilot_questions):,}')\n"
    "print(f'Unique pilot docs : {len(pilot_doc_ids)}')"
))

cells.append(code(
    "import pandas as pd\n"
    "\n"
    "n_unans       = sum(q['_unanswerable'] for q in pilot_questions)\n"
    "mean_q_words  = np.mean([q['_q_words'] for q in pilot_questions])\n"
    "mean_a_words  = np.mean([q['_a_words'] for q in pilot_questions])\n"
    "mean_pgs      = np.mean([q['total_doc_pages'] for q in pilot_questions])\n"
    "mean_ans_page = np.mean([q['_actual_answer_page'] for q in pilot_questions])\n"
    "\n"
    "print(f'=== Pilot Set Statistics (N={len(pilot_questions)}) ===')\n"
    "print(f'  Unanswerable       : {n_unans} (0.0% -- MP-DocVQA is fully answerable)')\n"
    "print(f'  Mean doc pages     : {mean_pgs:.1f}')\n"
    "print(f'  Mean answer page   : {mean_ans_page:.1f}')\n"
    "print(f'  Mean Q length (wds): {mean_q_words:.1f}')\n"
    "print(f'  Mean A length (wds): {mean_a_words:.1f}')\n"
    "print()\n"
    "print(f'Top-5 doc_ids by question count:')\n"
    "doc_q_count = Counter(q['doc_id'] for q in pilot_questions)\n"
    "for did, cnt in doc_q_count.most_common(5):\n"
    "    print(f'  {did}: {cnt} questions')"
))

# ── Phase 1.5 — EDA ───────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 1.5 -- Exploratory Data Analysis\n"
    "\n"
    "Comprehensive descriptive statistics, charts, and tables for the full\n"
    "MP-DocVQA val corpus and the pilot subset.  \n"
    "All figures saved to `results/figures/`.\n"
    "\n"
    "| Figure | Description |\n"
    "|---|---|\n"
    "| Fig 1 | Total pages per doc (histogram) + questions per unique doc (bar) |\n"
    "| Fig 2 | Answer page (absolute) + normalised answer position distributions |\n"
    "| Fig 3 | Question length + answer length distributions |\n"
    "| Fig 4 | Context span width + context start page distributions |\n"
    "| Fig 5 | Top-30 answer first words (answer type fingerprint) |\n"
    "| Fig 6 | Answer consensus (unique valid answers per question) |\n"
    "| Fig 7 | Pilot vs full val corpus key metrics comparison |"
))

cells.append(code(
    "import matplotlib\n"
    "matplotlib.use('Agg')   # non-interactive backend for nbconvert\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "import seaborn as sns\n"
    "\n"
    "sns.set_theme(style='whitegrid', palette='muted')\n"
    "FIG_DIR = RESULTS_DIR / 'figures'\n"
    "FIG_DIR.mkdir(exist_ok=True)\n"
    "\n"
    "# --- Full corpus derived stats -------------------------------------------\n"
    "N_ALL    = len(all_questions)\n"
    "N_DOCS   = len({q['doc_id'] for q in all_questions})\n"
    "MEAN_PGS = np.mean([q['total_doc_pages'] for q in all_questions])\n"
    "MAX_PGS  = max(q['total_doc_pages'] for q in all_questions)\n"
    "MEAN_QW  = np.mean([q['_q_words']    for q in all_questions])\n"
    "MEAN_AW  = np.mean([q['_a_words']    for q in all_questions])\n"
    "MEAN_ANS_PAGE = np.mean([q['_actual_answer_page'] for q in all_questions])\n"
    "\n"
    "overview = pd.DataFrame({\n"
    "    'Metric': [\n"
    "        'Total QA records', 'Unique documents',\n"
    "        'Unanswerable questions',\n"
    "        'Mean doc pages',\n"
    "        'Max doc pages',\n"
    "        'Mean answer page (absolute)',\n"
    "        'Mean question length (words)',\n"
    "        'Mean answer length (words)',\n"
    "    ],\n"
    "    'Full val (5,187)': [\n"
    "        f'{N_ALL:,}', f'{N_DOCS}',\n"
    "        '0 (0.0%)',\n"
    "        f'{MEAN_PGS:.1f}',\n"
    "        f'{MAX_PGS}',\n"
    "        f'{MEAN_ANS_PAGE:.1f}',\n"
    "        f'{MEAN_QW:.1f}',\n"
    "        f'{MEAN_AW:.1f}',\n"
    "    ],\n"
    "    f'Pilot (N={len(pilot_questions)})': [\n"
    "        f'{len(pilot_questions)}', f'{len(pilot_doc_ids)}',\n"
    "        '0 (0.0%)',\n"
    "        f'{np.mean([q[\"total_doc_pages\"] for q in pilot_questions]):.1f}',\n"
    "        f'{max(q[\"total_doc_pages\"] for q in pilot_questions)}',\n"
    "        f'{np.mean([q[\"_actual_answer_page\"] for q in pilot_questions]):.1f}',\n"
    "        f'{np.mean([q[\"_q_words\"] for q in pilot_questions]):.1f}',\n"
    "        f'{np.mean([q[\"_a_words\"] for q in pilot_questions]):.1f}',\n"
    "    ],\n"
    "})\n"
    "print('=== Corpus Overview ===')\n"
    "print(overview.to_string(index=False))"
))

cells.append(code(
    "# --- Figure 1: Doc pages distribution + questions per unique doc ----------\n"
    "total_pages = [q['total_doc_pages'] for q in all_questions]\n"
    "q_per_doc   = Counter(q['doc_id'] for q in all_questions)\n"
    "qpd_vals    = list(q_per_doc.values())\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('MP-DocVQA -- Document Length & Question Load (full val, N=5,187)', fontsize=13)\n"
    "\n"
    "# Total pages per doc (log-scale x)\n"
    "axes[0].hist(total_pages, bins=40, color=sns.color_palette('muted')[0], edgecolor='white')\n"
    "axes[0].set_xlabel('Total pages per document')\n"
    "axes[0].set_ylabel('Number of questions')\n"
    "axes[0].set_title(f'Document Length Distribution (mean={MEAN_PGS:.0f}, max={MAX_PGS})')\n"
    "axes[0].axvline(np.mean(total_pages), color='red', linestyle='--', linewidth=1.2, label=f'Mean {np.mean(total_pages):.0f}')\n"
    "axes[0].legend(fontsize=9)\n"
    "\n"
    "# Questions per unique doc\n"
    "qpd_counter = Counter(qpd_vals)\n"
    "sorted_counts = sorted(qpd_counter.items())\n"
    "x_vals = [k for k, _ in sorted_counts[:20]]\n"
    "y_vals = [v for _, v in sorted_counts[:20]]\n"
    "axes[1].bar(x_vals, y_vals, color=sns.color_palette('muted')[1], edgecolor='white')\n"
    "axes[1].set_xlabel('Questions per document')\n"
    "axes[1].set_ylabel('Number of documents')\n"
    "axes[1].set_title(f'Questions per Document (N={N_DOCS} unique docs, top 20)')\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig1_doc_length_dist.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig1_doc_length_dist.png')"
))

cells.append(code(
    "# --- Figure 2: Answer page distributions ---------------------------------\n"
    "ans_pages     = [q['_actual_answer_page'] for q in all_questions]\n"
    "norm_positions = [q['_actual_answer_page'] / max(q['total_doc_pages'] - 1, 1)\n"
    "                  for q in all_questions]\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4.5))\n"
    "fig.suptitle('MP-DocVQA -- Answer Page Location (full val)', fontsize=13)\n"
    "\n"
    "# Absolute answer page index\n"
    "axes[0].hist(ans_pages, bins=50, color=sns.color_palette('muted')[2], edgecolor='white')\n"
    "axes[0].set_xlabel('Absolute answer page index (0-based)')\n"
    "axes[0].set_ylabel('Number of questions')\n"
    "axes[0].set_title(f'Answer Page Distribution (mean={MEAN_ANS_PAGE:.1f})')\n"
    "axes[0].axvline(np.mean(ans_pages), color='red', linestyle='--', linewidth=1.2,\n"
    "                label=f'Mean {np.mean(ans_pages):.1f}')\n"
    "axes[0].legend(fontsize=9)\n"
    "\n"
    "# Normalised answer position [0, 1]\n"
    "axes[1].hist(norm_positions, bins=50, color=sns.color_palette('muted')[3], edgecolor='white')\n"
    "axes[1].set_xlabel('Normalised answer position (0 = first page, 1 = last page)')\n"
    "axes[1].set_ylabel('Number of questions')\n"
    "axes[1].set_title('Normalised Answer Position')\n"
    "axes[1].axvline(np.mean(norm_positions), color='red', linestyle='--', linewidth=1.2,\n"
    "                label=f'Mean {np.mean(norm_positions):.2f}')\n"
    "axes[1].legend(fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig2_answer_page_dist.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig2_answer_page_dist.png')"
))

cells.append(code(
    "# --- Figure 3: Question and answer word length distributions -------------\n"
    "q_words = [q['_q_words'] for q in all_questions]\n"
    "a_words = [q['_a_words'] for q in all_questions]\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\n"
    "fig.suptitle('MP-DocVQA -- Question & Answer Length Distributions (full val)', fontsize=13)\n"
    "\n"
    "axes[0].hist(q_words, bins=30, color=sns.color_palette('muted')[4], edgecolor='white')\n"
    "axes[0].set_xlabel('Question length (words)')\n"
    "axes[0].set_ylabel('Frequency')\n"
    "axes[0].set_title(f'Question Length (mean={MEAN_QW:.1f} words)')\n"
    "axes[0].axvline(np.mean(q_words), color='red', linestyle='--', linewidth=1.2)\n"
    "\n"
    "axes[1].hist(a_words, bins=20, color=sns.color_palette('muted')[5], edgecolor='white')\n"
    "axes[1].set_xlabel('Answer length (words)')\n"
    "axes[1].set_ylabel('Frequency')\n"
    "axes[1].set_title(f'Answer Length (mean={MEAN_AW:.1f} words)')\n"
    "axes[1].axvline(np.mean(a_words), color='red', linestyle='--', linewidth=1.2)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig3_qlen_alen_dist.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig3_qlen_alen_dist.png')"
))

cells.append(code(
    "# --- Figure 4: Context window span + start page distributions -----------\n"
    "# pages field is the context window given in the dataset (1-2 pages)\n"
    "span_widths  = [max(q['pages']) - min(q['pages']) + 1 for q in all_questions if q['pages']]\n"
    "start_pages  = [min(q['pages']) for q in all_questions if q['pages']]\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\n"
    "fig.suptitle('MP-DocVQA -- Context Window Characteristics (full val)', fontsize=13)\n"
    "\n"
    "# Span width (how many pages the dataset provides as context)\n"
    "span_counts = Counter(span_widths)\n"
    "sc_sorted   = sorted(span_counts.items())\n"
    "axes[0].bar([k for k, _ in sc_sorted], [v for _, v in sc_sorted],\n"
    "            color=sns.color_palette('muted')[0], edgecolor='white')\n"
    "axes[0].set_xlabel('Context span (pages)')\n"
    "axes[0].set_ylabel('Number of questions')\n"
    "axes[0].set_title(f'Context Window Span Width (mean={np.mean(span_widths):.2f})')\n"
    "\n"
    "# Context start page (how deep into the doc)\n"
    "axes[1].hist(start_pages, bins=40, color=sns.color_palette('muted')[1], edgecolor='white')\n"
    "axes[1].set_xlabel('Context start page (absolute)')\n"
    "axes[1].set_ylabel('Frequency')\n"
    "axes[1].set_title(f'Context Start Page (mean={np.mean(start_pages):.1f})')\n"
    "axes[1].axvline(np.mean(start_pages), color='red', linestyle='--', linewidth=1.2)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig4_context_window.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig4_context_window.png')"
))

cells.append(code(
    "# --- Figure 5: Top-30 answer first words (answer type fingerprint) -------\n"
    "first_words = Counter()\n"
    "for q in all_questions:\n"
    "    ans = q['answers'][0] if q['answers'] else ''\n"
    "    if ans:\n"
    "        first_word = ans.strip().lower().split()[0] if ans.strip() else ''\n"
    "        if first_word:\n"
    "            first_words[first_word] += 1\n"
    "\n"
    "top30 = first_words.most_common(30)\n"
    "fw_labels = [w for w, _ in top30]\n"
    "fw_vals   = [c for _, c in top30]\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(14, 6))\n"
    "colors  = sns.color_palette('tab20', len(fw_labels))\n"
    "bars    = ax.barh(fw_labels[::-1], fw_vals[::-1], color=colors)\n"
    "ax.set_xlabel('Frequency')\n"
    "ax.set_title('MP-DocVQA -- Top-30 Answer First Words (val corpus, N=5,187)', fontsize=13)\n"
    "for bar, val in zip(bars, fw_vals[::-1]):\n"
    "    ax.text(bar.get_width() + 2, bar.get_y() + bar.get_height()/2,\n"
    "            str(val), va='center', fontsize=8)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig5_answer_first_words.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig5_answer_first_words.png')"
))

cells.append(code(
    "# --- Figure 6: Answer consensus (unique valid answers per question) ------\n"
    "# How many distinct valid answers annotators provided\n"
    "n_unique_ans = [len(set(q['answers'])) for q in all_questions]\n"
    "n_total_ans  = [len(q['answers']) for q in all_questions]\n"
    "\n"
    "# Consensus score: 1.0 = all annotators agree, lower = more disagreement\n"
    "from collections import Counter as _C\n"
    "consensus_scores = []\n"
    "for q in all_questions:\n"
    "    if q['answers']:\n"
    "        most_common_count = _C(q['answers']).most_common(1)[0][1]\n"
    "        consensus_scores.append(most_common_count / len(q['answers']))\n"
    "    else:\n"
    "        consensus_scores.append(0.0)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\n"
    "fig.suptitle('MP-DocVQA -- Answer Annotation Agreement (full val)', fontsize=13)\n"
    "\n"
    "unique_counter = Counter(n_unique_ans)\n"
    "uc_sorted = sorted(unique_counter.items())\n"
    "axes[0].bar([k for k, _ in uc_sorted], [v for _, v in uc_sorted],\n"
    "            color=sns.color_palette('muted')[2], edgecolor='white')\n"
    "axes[0].set_xlabel('Unique valid answers per question')\n"
    "axes[0].set_ylabel('Number of questions')\n"
    "axes[0].set_title('Answer Diversity (1 = all annotators agree)')\n"
    "\n"
    "axes[1].hist(consensus_scores, bins=20, color=sns.color_palette('muted')[3], edgecolor='white')\n"
    "axes[1].set_xlabel('Consensus score (majority vote / total annotations)')\n"
    "axes[1].set_ylabel('Frequency')\n"
    "axes[1].set_title(f'Annotator Consensus (mean={np.mean(consensus_scores):.2f})')\n"
    "axes[1].axvline(np.mean(consensus_scores), color='red', linestyle='--', linewidth=1.2)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig6_answer_consensus.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig6_answer_consensus.png')"
))

cells.append(code(
    "# --- Figure 7: Pilot vs full val comparison (5 key metrics) -------------\n"
    "labels  = ['Total Qs', 'Unique docs', 'Mean doc pages', 'Mean Q len (wds)', 'Mean A len (wds)']\n"
    "full_vals  = [N_ALL, N_DOCS, MEAN_PGS, MEAN_QW, MEAN_AW]\n"
    "pilot_vals = [\n"
    "    len(pilot_questions),\n"
    "    len(pilot_doc_ids),\n"
    "    np.mean([q['total_doc_pages'] for q in pilot_questions]),\n"
    "    np.mean([q['_q_words'] for q in pilot_questions]),\n"
    "    np.mean([q['_a_words'] for q in pilot_questions]),\n"
    "]\n"
    "\n"
    "x      = np.arange(len(labels))\n"
    "width  = 0.35\n"
    "norm_full  = [1.0] * len(labels)   # full = 100%\n"
    "norm_pilot = [p / f if f else 0.0 for p, f in zip(pilot_vals, full_vals)]\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('MP-DocVQA -- Pilot vs Full Val Corpus', fontsize=13)\n"
    "\n"
    "# Raw values\n"
    "axes[0].bar(x - width/2, full_vals,  width, label='Full val',       color=sns.color_palette('muted')[0])\n"
    "axes[0].bar(x + width/2, pilot_vals, width, label=f'Pilot (N={N_PILOT})', color=sns.color_palette('muted')[1])\n"
    "axes[0].set_xticks(x)\n"
    "axes[0].set_xticklabels(labels, rotation=18, ha='right', fontsize=8)\n"
    "axes[0].set_title('Raw Values')\n"
    "axes[0].legend(fontsize=9)\n"
    "\n"
    "# Pilot as fraction of full\n"
    "axes[1].bar(x, norm_pilot, width=0.5, color=sns.color_palette('muted')[2])\n"
    "axes[1].axhline(1.0, color='red', linestyle='--', linewidth=1, label='Full = 1.0')\n"
    "axes[1].set_xticks(x)\n"
    "axes[1].set_xticklabels(labels, rotation=18, ha='right', fontsize=8)\n"
    "axes[1].set_title('Pilot as Fraction of Full Val')\n"
    "axes[1].set_ylim(0, 1.3)\n"
    "axes[1].legend(fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig7_pilot_vs_full.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig7_pilot_vs_full.png')"
))

cells.append(code(
    "# --- Table: Sample QA pairs (3 per answer type) -------------------------\n"
    "# Categorise answers: numeric, short-text (1-2 words), longer-text (3+ words)\n"
    "def answer_category(ans):\n"
    "    try:\n"
    "        float(ans.replace(',', '').replace('%', ''))\n"
    "        return 'Numeric'\n"
    "    except (ValueError, AttributeError):\n"
    "        pass\n"
    "    words = ans.strip().split()\n"
    "    return 'Short-text (1-2 wds)' if len(words) <= 2 else 'Longer-text (3+ wds)'\n"
    "\n"
    "print('=== Sample QA Pairs by Answer Category ===')\n"
    "for cat in ['Numeric', 'Short-text (1-2 wds)', 'Longer-text (3+ wds)']:\n"
    "    samples = [q for q in all_questions\n"
    "               if q['answers'] and answer_category(q['answers'][0]) == cat][:3]\n"
    "    if not samples:\n"
    "        continue\n"
    "    n_total = sum(1 for q in all_questions\n"
    "                  if q['answers'] and answer_category(q['answers'][0]) == cat)\n"
    "    print(f'\\n--- {cat} ({n_total} questions) ---')\n"
    "    for q in samples:\n"
    "        ans_display = q['answers'][0][:80]\n"
    "        print(f'  Q: {q[\"question\"][:90]}')\n"
    "        print(f'  A: {ans_display}')\n"
    "        print(f'  doc_id={q[\"doc_id\"]}  page={q[\"_actual_answer_page\"]}  total_pages={q[\"total_doc_pages\"]}')\n"
    "        print()"
))

# ── Phase 2 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 2 -- Verify OCR & Image File Coverage\n"
    "\n"
    "MP-DocVQA data is already local -- no download required.  \n"
    "This phase verifies that all pilot documents have their corresponding\n"
    "OCR JSON files (`ocr/ocr/{doc_id}_p{N}.json`) and page images\n"
    "(`images/images/{doc_id}_p{N}.jpg`) available.  \n"
    "\n"
    "OCR location: `data/mpdocvqa/ocr/ocr/`  \n"
    "Images location: `data/mpdocvqa/images/images/`"
))

cells.append(code(
    "# Resolve the actual OCR subdirectory (handles nested ocr/ocr/ layout)\n"
    "actual_ocr_dir = OCR_DIR\n"
    "nested_ocr = OCR_DIR / OCR_DIR.name\n"
    "if nested_ocr.exists() and any(nested_ocr.glob('*.json')):\n"
    "    actual_ocr_dir = nested_ocr\n"
    "\n"
    "actual_img_dir = IMG_DIR\n"
    "nested_img = IMG_DIR / IMG_DIR.name\n"
    "if nested_img.exists() and any(nested_img.glob('*.jpg')):\n"
    "    actual_img_dir = nested_img\n"
    "\n"
    "print(f'OCR directory : {actual_ocr_dir}')\n"
    "print(f'Image directory: {actual_img_dir}')\n"
    "\n"
    "# Check OCR coverage for pilot docs\n"
    "missing_ocr   = []\n"
    "missing_img   = []\n"
    "parseable_docs = []\n"
    "\n"
    "for doc_id in pilot_doc_ids:\n"
    "    ocr_files = list(actual_ocr_dir.glob(f'{doc_id}_p*.json'))\n"
    "    img_files = list(actual_img_dir.glob(f'{doc_id}_p*.jpg'))\n"
    "    if not ocr_files:\n"
    "        missing_ocr.append(doc_id)\n"
    "    if not img_files:\n"
    "        missing_img.append(doc_id)\n"
    "    if ocr_files:\n"
    "        parseable_docs.append(doc_id)\n"
    "\n"
    "print(f'\\nPilot docs    : {len(pilot_doc_ids)}')\n"
    "print(f'With OCR files: {len(parseable_docs)} ({len(parseable_docs)}/{len(pilot_doc_ids)})')\n"
    "print(f'With images   : {len(pilot_doc_ids)-len(missing_img)} ({len(pilot_doc_ids)-len(missing_img)}/{len(pilot_doc_ids)})')\n"
    "if missing_ocr:\n"
    "    print(f'Warning: Missing OCR for: {missing_ocr[:5]}')\n"
    "if missing_img:\n"
    "    print(f'Warning: Missing images for: {missing_img[:5]}')\n"
    "\n"
    "# Spot-check: count OCR pages for first 3 pilot docs\n"
    "for doc_id in parseable_docs[:3]:\n"
    "    n_ocr = len(list(actual_ocr_dir.glob(f'{doc_id}_p*.json')))\n"
    "    n_img = len(list(actual_img_dir.glob(f'{doc_id}_p*.jpg')))\n"
    "    print(f'  {doc_id}: {n_ocr} OCR pages, {n_img} images')"
))

# ── Phase 3 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 3 -- Parse Documents with mpdocvqa_parser + Temporal Annotation\n"
    "\n"
    "The `mpdocvqa_parser` converts AWS Textract OCR JSON files (one per page) into\n"
    "the GraMM-RAG element format used by graph builder and embeddings.  \n"
    "No MinerU required -- all data is already in text form.\n"
    "\n"
    "Output: `parsed/mpdocvqa/{doc_id}.json` for each pilot document.  \n"
    "**Runtime:** ~1-5 s/doc (pure JSON parsing, no GPU needed)."
))

cells.append(code(
    "from src.parsing.mpdocvqa_parser import parse_mpdocvqa_doc_from_pages\n"
    "\n"
    "parsed_count = skip_count = fail_count = 0\n"
    "\n"
    "for doc_id in parseable_docs:\n"
    "    out_path  = PARSED_DIR / f'{doc_id}.json'\n"
    "    if out_path.exists():\n"
    "        skip_count += 1\n"
    "        continue\n"
    "\n"
    "    page_files = sorted(actual_ocr_dir.glob(f'{doc_id}_p*.json'),\n"
    "                        key=lambda p: int(re.search(r'_p(\\d+)', p.stem).group(1)))\n"
    "    if not page_files:\n"
    "        logger.warning(f'No OCR files for {doc_id}')\n"
    "        fail_count += 1\n"
    "        continue\n"
    "    try:\n"
    "        parsed = parse_mpdocvqa_doc_from_pages(page_files, doc_id)\n"
    "        out_path.write_text(json.dumps(parsed, indent=2), encoding='utf-8')\n"
    "        parsed_count += 1\n"
    "    except Exception as e:\n"
    "        logger.error(f'Parse failed {doc_id}: {e}')\n"
    "        fail_count += 1\n"
    "\n"
    "print(f'Parsed: {parsed_count}, Skipped (cached): {skip_count}, Failed: {fail_count}')\n"
    "parsed_ids = {p.stem for p in PARSED_DIR.glob('*.json')}\n"
    "print(f'Total parsed docs available: {len(parsed_ids)}')"
))

cells.append(code(
    "from src.parsing.temporal import annotate_parsed_elements\n"
    "\n"
    "annotated = 0\n"
    "for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "    try:\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "        if any('temporal_markers' in e for e in parsed.get('elements', [])):\n"
    "            continue\n"
    "        parsed = annotate_parsed_elements(parsed, None, use_llm_fallback=False)\n"
    "        pf.write_text(json.dumps(parsed, indent=2), encoding='utf-8')\n"
    "        annotated += 1\n"
    "    except Exception as e:\n"
    "        logger.warning(f'Temporal annotation failed {pf.name}: {e}')\n"
    "\n"
    "print(f'Temporal annotation: {annotated} docs annotated')"
))

# ── Phase 4 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 4 -- Node Embeddings + PyG Graph Construction\n"
    "\n"
    "**Text nodes** (all elements in MP-DocVQA are text type):  \n"
    "E5-Mistral-7B-Instruct (4-bit, ~4 GB VRAM) -> 256-dim projection.  \n"
    "Fallback: E5-large-v2 on CPU.\n"
    "\n"
    "**No image nodes:** MP-DocVQA parsed elements are all `text` type (Textract LINE blocks).  \n"
    "KG triplets: GPT-4o-mini extraction (skipped if `OPENAI_API_KEY` not set).  \n"
    "\n"
    "**Runtime:** ~30-120 s/doc (embedding only, no PDF rendering)."
))

cells.append(code(
    "if SKIP_EMBEDDING:\n"
    "    print('SKIP_EMBEDDING=True (pilot+CPU): skipping neural embedding step.')\n"
    "    print('  Phases 5-9 will use random-init HGT graphs (no FAISS indices).')\n"
    "    print('  Set SKIP_EMBEDDING=False with a GPU for full embedding.')\n"
    "else:\n"
    "    from src.graph.embeddings import compute_and_save_embeddings\n"
    "\n"
    "    embedded_count = skip_emb_count = 0\n"
    "\n"
    "    for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "        doc_id  = pf.stem\n"
    "        text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "        img_pt  = EMB_DIR / f'{doc_id}_img.pt'\n"
    "        if text_pt.exists() and img_pt.exists():\n"
    "            skip_emb_count += 1\n"
    "            continue\n"
    "        try:\n"
    "            parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "            if MAX_PAGES_PILOT is not None:\n"
    "                parsed = dict(parsed)\n"
    "                parsed['elements'] = [e for e in parsed.get('elements', [])\n"
    "                                       if e.get('page_no', 0) < MAX_PAGES_PILOT]\n"
    "            compute_and_save_embeddings(\n"
    "                parsed,\n"
    "                embeddings_dir=str(EMB_DIR),\n"
    "                image_root=str(actual_img_dir),\n"
    "                device=DEVICE,\n"
    "                text_batch_size=16,\n"
    "                image_batch_size=8,\n"
    "            )\n"
    "            embedded_count += 1\n"
    "        except Exception as e:\n"
    "            logger.error(f'Embedding failed {doc_id}: {e}')\n"
    "\n"
    "    print(f'Embeddings computed: {embedded_count}, Skipped (cached): {skip_emb_count}')"
))

cells.append(code(
    "from src.graph.edges import extract_all_triplets\n"
    "from src.graph.builder import build_graph, save_graph\n"
    "\n"
    "openai_client_kg = None\n"
    "if os.environ.get('OPENAI_API_KEY'):\n"
    "    try:\n"
    "        import openai\n"
    "        openai_client_kg = openai.OpenAI(api_key=os.environ['OPENAI_API_KEY'])\n"
    "        print('OpenAI client ready for KG extraction')\n"
    "    except ImportError:\n"
    "        print('openai package not found -- KG triplets empty')\n"
    "else:\n"
    "    print('No OPENAI_API_KEY -- KG triplets empty (graph still built)')\n"
    "\n"
    "EMBED_DIM  = 256   # projection dim used by DocumentHGT\n"
    "graph_count = skip_graph = 0\n"
    "\n"
    "for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "    doc_id  = pf.stem\n"
    "    if (GRAPH_DIR / f'{doc_id}.pt').exists():\n"
    "        skip_graph += 1\n"
    "        continue\n"
    "    text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "    img_pt  = EMB_DIR / f'{doc_id}_img.pt'\n"
    "    try:\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "        parsed.setdefault('doc_id', doc_id)\n"
    "        n_text = len([e for e in parsed.get('elements', []) if e['type'] == 'text'])\n"
    "        if text_pt.exists():\n"
    "            text_emb = torch.load(text_pt, weights_only=True)\n"
    "        else:\n"
    "            # SKIP_EMBEDDING path: random-init embeddings (enables graph structure)\n"
    "            text_emb = torch.nn.init.xavier_uniform_(\n"
    "                torch.empty(max(n_text, 1), EMBED_DIM))\n"
    "        img_emb = (torch.load(img_pt, weights_only=True)\n"
    "                   if img_pt.exists() else torch.zeros(0, EMBED_DIM))\n"
    "        embeddings = {'text': text_emb, 'img': img_emb}\n"
    "        triplets = []\n"
    "        if openai_client_kg:\n"
    "            try:\n"
    "                triplets = extract_all_triplets(parsed, openai_client_kg)\n"
    "            except Exception as e:\n"
    "                logger.warning(f'KG extraction failed {doc_id}: {e}')\n"
    "        graph = build_graph(doc_id, parsed, embeddings, triplets)\n"
    "        save_graph(graph, str(GRAPH_DIR), doc_id)\n"
    "        graph_count += 1\n"
    "    except Exception as e:\n"
    "        logger.error(f'Graph build failed {doc_id}: {e}')\n"
    "\n"
    "emb_note = '(random-init)' if SKIP_EMBEDDING else '(neural)'\n"
    "print(f'Graphs built {emb_note}: {graph_count}, Skipped (cached): {skip_graph}')\n"
    "print(f'Total graphs available: {len(list(GRAPH_DIR.glob(\"*.pt\")))}')"
))

# ── Phase 5 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 5 -- Train HGT with Evidence-Guided InfoNCE Loss\n"
    "\n"
    "Uses MP-DocVQA `answer_page_idx` + `pages` to identify the answer page as evidence:\n"
    "- **Anchor:** mean of all text node embeddings (query proxy)\n"
    "- **Positive:** text nodes on the answer page (`pages[answer_page_idx]`)\n"
    "- **Negatives:** 15 random non-answer-page nodes\n"
    "\n"
    "Saved to `results/models/hgt_mpdocvqa/best_model.pt`."
))

cells.append(code(
    "from src.retrieval.hgt_model import DocumentHGT, info_nce_loss, METADATA\n"
    "from src.graph.builder import load_graph\n"
    "\n"
    "def get_evidence_node_indices_mpdocvqa(parsed, answer_page, node_type='text'):\n"
    "    \"\"\"Return indices of elements on the answer page for a given node type.\"\"\"\n"
    "    typed = [e for e in parsed['elements'] if e['type'] == node_type]\n"
    "    return [i for i, e in enumerate(typed) if e.get('page_no', -1) == answer_page]\n"
    "\n"
    "def build_hgt_triple_mpdocvqa(item, model, GRAPH_DIR, PARSED_DIR, device):\n"
    "    doc_id      = item['doc_id']\n"
    "    answer_page = item['_actual_answer_page']\n"
    "    graph = load_graph(str(GRAPH_DIR), doc_id)\n"
    "    if graph is None:\n"
    "        return None\n"
    "    pf = PARSED_DIR / f'{doc_id}.json'\n"
    "    if not pf.exists():\n"
    "        return None\n"
    "    parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "\n"
    "    x_dict = {nt: graph[nt].x.to(device)\n"
    "              for nt in graph.node_types\n"
    "              if hasattr(graph[nt], 'x') and graph[nt].x.shape[0] > 0}\n"
    "    edge_index_dict = {et: graph[et].edge_index.to(device)\n"
    "                       for et in graph.edge_types\n"
    "                       if graph[et].edge_index.shape[1] > 0}\n"
    "    if not x_dict:\n"
    "        return None\n"
    "\n"
    "    out_dict = model(x_dict, edge_index_dict)\n"
    "    text_out = out_dict.get('text')\n"
    "    if text_out is None or text_out.shape[0] == 0:\n"
    "        return None\n"
    "    q_emb = torch.nn.functional.normalize(text_out.mean(0), dim=-1)\n"
    "\n"
    "    # Positive: nodes on the answer page\n"
    "    pos_idxs = get_evidence_node_indices_mpdocvqa(parsed, answer_page, 'text')\n"
    "    pos_embs = [torch.nn.functional.normalize(text_out[i], dim=-1)\n"
    "                for i in pos_idxs if i < text_out.shape[0]]\n"
    "\n"
    "    all_embs = torch.cat([e for e in out_dict.values() if e.shape[0] > 0])\n"
    "    if all_embs.shape[0] < 2:\n"
    "        return None\n"
    "    pos_emb = (random.choice(pos_embs) if pos_embs\n"
    "               else torch.nn.functional.normalize(\n"
    "                    all_embs[random.randint(0, all_embs.shape[0]-1)], dim=-1))\n"
    "\n"
    "    n_neg    = min(15, all_embs.shape[0] - 1)\n"
    "    perm     = torch.randperm(all_embs.shape[0])[:n_neg]\n"
    "    neg_embs = torch.nn.functional.normalize(all_embs[perm], dim=-1)\n"
    "    return q_emb, pos_emb, neg_embs\n"
    "\n"
    "print('HGT training helpers defined.')"
))

cells.append(code(
    "random.seed(SEED)\n"
    "torch.manual_seed(SEED)\n"
    "\n"
    "available_graph_ids = [p.stem for p in GRAPH_DIR.glob('*.pt')]\n"
    "graph_id_set        = set(available_graph_ids)\n"
    "\n"
    "doc_to_questions = defaultdict(list)\n"
    "for q in pilot_questions:\n"
    "    if q['doc_id'] in graph_id_set:\n"
    "        doc_to_questions[q['doc_id']].append(q)\n"
    "\n"
    "print(f'HGT_EPOCHS = {HGT_EPOCHS}')\n"
    "print(f'Training graphs available: {len(available_graph_ids)}')\n"
    "print(f'Docs with questions: {len(doc_to_questions)}')\n"
    "\n"
    "if hgt_save_path.exists():\n"
    "    print(f'HGT already trained: {hgt_save_path}')\n"
    "elif not available_graph_ids:\n"
    "    print('No graphs available. Run Phase 4 first to build graphs.')\n"
    "else:\n"
    "    hgt_model = DocumentHGT(metadata=METADATA).to(DEVICE)\n"
    "    optimizer = torch.optim.Adam(hgt_model.parameters(), lr=1e-3, weight_decay=1e-4)\n"
    "    best_loss = float('inf')\n"
    "\n"
    "    for epoch in range(HGT_EPOCHS):\n"
    "        hgt_model.train()\n"
    "        total_loss = n_batches = 0\n"
    "        all_qs = [q for qs in doc_to_questions.values() for q in qs]\n"
    "        random.shuffle(all_qs)\n"
    "        for item in all_qs:\n"
    "            triple = build_hgt_triple_mpdocvqa(item, hgt_model, GRAPH_DIR, PARSED_DIR, DEVICE)\n"
    "            if triple is None:\n"
    "                continue\n"
    "            q_emb, pos_emb, neg_embs = triple\n"
    "            optimizer.zero_grad()\n"
    "            loss = info_nce_loss(q_emb, pos_emb, neg_embs)\n"
    "            if not (torch.isnan(loss) or torch.isinf(loss)):\n"
    "                loss.backward()\n"
    "                optimizer.step()\n"
    "                total_loss += loss.item()\n"
    "                n_batches  += 1\n"
    "        avg_loss = total_loss / max(n_batches, 1)\n"
    "        print(f'Epoch {epoch+1:3d}/{HGT_EPOCHS}  loss={avg_loss:.4f}  batches={n_batches}')\n"
    "        if avg_loss < best_loss:\n"
    "            best_loss = avg_loss\n"
    "            hgt_save_path.parent.mkdir(parents=True, exist_ok=True)\n"
    "            torch.save(hgt_model.state_dict(), hgt_save_path)\n"
    "\n"
    "    print(f'HGT training done. Best loss={best_loss:.4f}  Saved: {hgt_save_path}')"
))

# ── Phase 6 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 6 -- Train Query Router (DeBERTa-v3-base)\n"
    "\n"
    "Auto-annotate routing labels from MP-DocVQA metadata:\n"
    "- **GRAPH** -- answer is deep in doc (actual answer page > 5) -- cross-page navigation needed\n"
    "- **VECTOR** -- answer is on early pages (answer page <= 5) -- simple lookup may suffice\n"
    "- **HYBRID** -- not used (MP-DocVQA is text-only, no Chart/Figure/Table evidence)\n"
    "\n"
    "Pilot mode skips DeBERTa fine-tuning (too slow on CPU).  \n"
    "Phase 9 uses the heuristic regex router as fallback.  \n"
    "Full run (`N_PILOT=None`): fine-tunes on all 5,187 val questions.  \n"
    "Saved to `results/models/router_mpdocvqa/best_model/`."
))

cells.append(code(
    "from src.retrieval.router import LABEL2ID\n"
    "\n"
    "# Build router samples: GRAPH if answer is deep in document, else VECTOR\n"
    "# (MP-DocVQA has no visual elements so HYBRID is not used)\n"
    "def make_router_samples(questions):\n"
    "    samples = []\n"
    "    for q in questions:\n"
    "        ans_page = q['_actual_answer_page']\n"
    "        total_p  = q['total_doc_pages']\n"
    "        # Heuristic: answer beyond page 5 in a long doc = GRAPH routing\n"
    "        label = 'GRAPH' if (ans_page > 5 and total_p > 10) else 'VECTOR'\n"
    "        samples.append({'query': q['question'], 'label': label})\n"
    "    return samples\n"
    "\n"
    "samples = make_router_samples(all_questions)\n"
    "label_counts = Counter(s['label'] for s in samples)\n"
    "print(f'Router training samples: {len(samples)}')\n"
    "print(f'Label distribution: {dict(label_counts)}')\n"
    "print(f'(HYBRID=0: MP-DocVQA is text-only, no visual routing needed)')"
))

cells.append(code(
    "from datasets import Dataset\n"
    "from transformers import (\n"
    "    AutoTokenizer, AutoModelForSequenceClassification,\n"
    "    TrainingArguments, Trainer\n"
    ")\n"
    "\n"
    "# -- Pilot mode: skip DeBERTa fine-tuning (CPU training >10 min per epoch)\n"
    "# -- Phase 9 will use the heuristic router fallback (regex-based routing)\n"
    "# -- Full run (N_PILOT=None): fine-tune DeBERTa for ROUTER_EPOCHS epochs\n"
    "\n"
    "if N_PILOT:\n"
    "    print('Pilot mode: skipping DeBERTa fine-tuning.')\n"
    "    print('  Phase 9 will use the heuristic router (regex-based).')\n"
    "    print('  Set N_PILOT=None for full DeBERTa fine-tuning (3 epochs).')\n"
    "elif router_save_dir.exists() and any(router_save_dir.iterdir()):\n"
    "    print(f'Router already trained: {router_save_dir}')\n"
    "else:\n"
    "    print(f'ROUTER_EPOCHS = {ROUTER_EPOCHS}')\n"
    "    id2label = {0: 'GRAPH', 1: 'VECTOR', 2: 'HYBRID'}\n"
    "    label2id = {v: k for k, v in id2label.items()}\n"
    "    ds = Dataset.from_dict({\n"
    "        'text':  [s['query'] for s in samples],\n"
    "        'label': [label2id[s['label']] for s in samples],\n"
    "    })\n"
    "    split    = ds.train_test_split(test_size=0.15, seed=SEED)\n"
    "    train_ds = split['train']\n"
    "    val_ds   = split['test']\n"
    "\n"
    "    model_name = 'microsoft/deberta-v3-base'\n"
    "    tokenizer  = AutoTokenizer.from_pretrained(model_name)\n"
    "\n"
    "    def tokenize(batch):\n"
    "        return tokenizer(batch['text'], truncation=True,\n"
    "                         max_length=128, padding='max_length')\n"
    "\n"
    "    train_enc = train_ds.map(tokenize, batched=True)\n"
    "    val_enc   = val_ds.map(tokenize,   batched=True)\n"
    "\n"
    "    router_model = AutoModelForSequenceClassification.from_pretrained(\n"
    "        model_name, num_labels=3,\n"
    "        id2label=id2label, label2id=label2id,\n"
    "    )\n"
    "\n"
    "    def compute_metrics(eval_pred):\n"
    "        logits, labels = eval_pred\n"
    "        preds = np.argmax(logits, axis=-1)\n"
    "        return {'accuracy': float((preds == labels).mean())}\n"
    "\n"
    "    training_args = TrainingArguments(\n"
    "        output_dir=str(MODEL_DIR / 'router_mpdocvqa'),\n"
    "        num_train_epochs=ROUTER_EPOCHS,\n"
    "        per_device_train_batch_size=8,\n"
    "        per_device_eval_batch_size=8,\n"
    "        learning_rate=2e-5,\n"
    "        weight_decay=0.01,\n"
    "        eval_strategy='epoch',\n"
    "        save_strategy='epoch',\n"
    "        load_best_model_at_end=True,\n"
    "        metric_for_best_model='accuracy',\n"
    "        logging_steps=50,\n"
    "        seed=SEED,\n"
    "        report_to='none',\n"
    "    )\n"
    "    trainer = Trainer(\n"
    "        model=router_model, args=training_args,\n"
    "        train_dataset=train_enc, eval_dataset=val_enc,\n"
    "        compute_metrics=compute_metrics,\n"
    "    )\n"
    "    trainer.train()\n"
    "    trainer.save_model(str(router_save_dir))\n"
    "    tokenizer.save_pretrained(str(router_save_dir))\n"
    "    res = trainer.evaluate()\n"
    "    print(f'Router val accuracy: {res.get(\"eval_accuracy\", 0):.4f}')\n"
    "    print(f'Saved: {router_save_dir}')"
))

# ── Phase 7 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 7 -- Tune Reward Function (alpha, beta, lambda, tau Grid Search)\n"
    "\n"
    "`R(q,K) = alpha*C + beta*S + lambda*T` -- C=coverage, S=similarity, T=temporal coherence\n"
    "\n"
    "Grid search on a 20% holdout of pilot questions.  \n"
    "Tuning signal: Spearman correlation between reward score and answer-page hit rate."
))

cells.append(code(
    "from src.retrieval.hgt_model import retrieve_top_k\n"
    "from src.retrieval.self_healing import RewardFunction\n"
    "import itertools\n"
    "\n"
    "hgt_model_tune = DocumentHGT(metadata=METADATA).to(DEVICE)\n"
    "if hgt_save_path.exists():\n"
    "    hgt_model_tune.load_state_dict(\n"
    "        torch.load(hgt_save_path, map_location=DEVICE, weights_only=False))\n"
    "    print(f'HGT loaded: {hgt_save_path}')\n"
    "else:\n"
    "    print('HGT not trained yet -- using random-init weights for reward tuning')\n"
    "hgt_model_tune.eval()\n"
    "\n"
    "random.seed(SEED + 1)\n"
    "tuning_qs = random.sample(pilot_questions, max(4, int(0.2 * len(pilot_questions))))\n"
    "print(f'Reward tuning on {len(tuning_qs)} held-out questions')\n"
    "\n"
    "grid = [(a, b, l, t)\n"
    "        for a, b, l, t in itertools.product(\n"
    "            [0.30, 0.40, 0.50], [0.30, 0.35, 0.40],\n"
    "            [0.20, 0.25, 0.30], [0.40, 0.50, 0.60, 0.70])\n"
    "        if abs(a + b + l - 1.0) <= 0.05]\n"
    "print(f'Grid size (weight-valid): {len(grid)} configurations')\n"
    "\n"
    "if reward_save.exists():\n"
    "    print(f'Reward params already tuned: {reward_save}')\n"
    "else:\n"
    "    best_score, best_params = -1.0, None\n"
    "    for alpha, beta, lambda_, tau in grid:\n"
    "        rf = RewardFunction(alpha=alpha, beta=beta, lambda_=lambda_, tau=tau)\n"
    "        scores, hits = [], []\n"
    "        for item in tuning_qs:\n"
    "            doc_id = item['doc_id']\n"
    "            graph  = load_graph(str(GRAPH_DIR), doc_id)\n"
    "            pf     = PARSED_DIR / f'{doc_id}.json'\n"
    "            if graph is None or not pf.exists():\n"
    "                continue\n"
    "            parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "            with torch.no_grad():\n"
    "                node_emb_dict = hgt_model_tune.encode_nodes(\n"
    "                    {nt: graph[nt].x.to(DEVICE) for nt in graph.node_types\n"
    "                     if hasattr(graph[nt], 'x') and graph[nt].x.shape[0] > 0},\n"
    "                    {et: graph[et].edge_index.to(DEVICE) for et in graph.edge_types\n"
    "                     if graph[et].edge_index.shape[1] > 0},\n"
    "                )\n"
    "            text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "            q_emb = (torch.load(text_pt, weights_only=True).mean(0)\n"
    "                     if text_pt.exists() else torch.zeros(256))\n"
    "            nodes = retrieve_top_k(q_emb, node_emb_dict, top_k=10)\n"
    "            rd    = rf.compute(q_emb, nodes, node_emb_dict, parsed, [])\n"
    "            scores.append(rd['reward'])\n"
    "            # Hit: did retrieval find any node on the answer page?\n"
    "            ev_page = item['_actual_answer_page']\n"
    "            ret_pages = set()\n"
    "            for n in nodes:\n"
    "                typed = [e for e in parsed['elements'] if e['type'] == n['node_type']]\n"
    "                if n['local_idx'] < len(typed):\n"
    "                    ret_pages.add(typed[n['local_idx']].get('page_no', -1))\n"
    "            hits.append(1.0 if ev_page in ret_pages else 0.0)\n"
    "        if len(scores) > 2 and sum(hits) > 0:\n"
    "            from scipy.stats import spearmanr\n"
    "            corr, _ = spearmanr(scores, hits)\n"
    "            corr = 0.0 if corr != corr else float(corr)\n"
    "        else:\n"
    "            corr = 0.0\n"
    "        if corr > best_score:\n"
    "            best_score = corr\n"
    "            best_params = {'alpha': alpha, 'beta': beta, 'lambda_': lambda_, 'tau': tau}\n"
    "\n"
    "    if best_params is None:\n"
    "        best_params = {'alpha': 0.40, 'beta': 0.35, 'lambda_': 0.25, 'tau': 0.60}\n"
    "        print('Grid search inconclusive. Using defaults.')\n"
    "    reward_save.parent.mkdir(parents=True, exist_ok=True)\n"
    "    reward_save.write_text(json.dumps(best_params, indent=2), encoding='utf-8')\n"
    "    print(f'Best reward params (corr={best_score:.3f}): {best_params}')\n"
    "\n"
    "print('Reward tuning complete.')"
))

# ── Phase 8 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 8 -- Flat-Vector RAG Baseline\n"
    "\n"
    "Baseline: FAISS vector search (no graph, no self-healing) + LLM.  \n"
    "Uses the same VLM backend as GraMM-RAG to isolate retrieval contribution.  \n"
    "Gold: `valid_answers` list (ANLS computed as max over all valid answers).  \n"
    "\n"
    "Results saved to `results/baseline_vector_mpdocvqa_pilot.json`."
))

cells.append(code(
    "from src.retrieval.vector_retrieval import VectorIndex\n"
    "from src.generation.prompt_builder import build_prompt\n"
    "from src.generation.vlm_client import VLMClient\n"
    "from src.evaluation.metrics import compute_all_metrics\n"
    "\n"
    "faiss_indices = {}\n"
    "\n"
    "for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "    doc_id     = pf.stem\n"
    "    index_path = EMB_DIR / f'{doc_id}_faiss.index'\n"
    "    text_pt    = EMB_DIR / f'{doc_id}_text.pt'\n"
    "\n"
    "    vi = VectorIndex()\n"
    "    if index_path.exists():\n"
    "        try:\n"
    "            vi.load(str(index_path))\n"
    "            faiss_indices[doc_id] = vi\n"
    "            continue\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "    if not text_pt.exists():\n"
    "        continue\n"
    "    try:\n"
    "        parsed   = json.loads(pf.read_text(encoding='utf-8'))\n"
    "        text_emb = torch.load(text_pt, weights_only=True)\n"
    "        # MP-DocVQA: all elements are text type; img_emb is empty\n"
    "        elements = parsed.get('elements', [])\n"
    "        tc       = Counter(e['type'] for e in elements)\n"
    "        node_emb_dict = {}\n"
    "        cur = 0\n"
    "        for nt, cnt in [('text', tc.get('text', 0)),\n"
    "                         ('section', tc.get('section', 0)),\n"
    "                         ('equation', tc.get('equation', 0))]:\n"
    "            if cnt > 0 and cur < text_emb.shape[0]:\n"
    "                end = min(cur + cnt, text_emb.shape[0])\n"
    "                node_emb_dict[nt] = text_emb[cur:end]\n"
    "                cur = end\n"
    "        if node_emb_dict:\n"
    "            vi.build(node_emb_dict, parsed, doc_id)\n"
    "            if vi.index is not None:\n"
    "                vi.save(str(index_path))\n"
    "                faiss_indices[doc_id] = vi\n"
    "    except Exception as e:\n"
    "        logger.warning(f'FAISS build failed {doc_id}: {e}')\n"
    "\n"
    "print(f'FAISS indices built: {len(faiss_indices)}')"
))

cells.append(code(
    "if vector_out_path.exists():\n"
    "    print(f'Flat-vector RAG results exist: {vector_out_path}')\n"
    "    vector_results = json.loads(vector_out_path.read_text())\n"
    "else:\n"
    "    vlm_vec = VLMClient(provider='together')\n"
    "    v_preds, v_golds, v_refused = [], [], []\n"
    "\n"
    "    for i, item in enumerate(pilot_questions):\n"
    "        question = item['question']\n"
    "        gold     = item['answers']   # list of valid answers for ANLS\n"
    "        doc_id   = item['doc_id']\n"
    "\n"
    "        text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "        q_emb   = (torch.load(text_pt, weights_only=True).mean(0)\n"
    "                   if text_pt.exists() else torch.zeros(256))\n"
    "\n"
    "        vi    = faiss_indices.get(doc_id)\n"
    "        nodes = vi.search(q_emb, top_k=10) if vi and vi.index else []\n"
    "\n"
    "        pf     = PARSED_DIR / f'{doc_id}.json'\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8')) if pf.exists() else {'elements': []}\n"
    "\n"
    "        prompt = build_prompt(question, nodes, parsed, {}, False,\n"
    "                              benchmark='mpdocvqa')\n"
    "        answer = vlm_vec.generate(prompt, temperature=0.0, max_tokens=128)\n"
    "\n"
    "        v_preds.append(answer)\n"
    "        v_golds.append(gold)     # list for multi-annotator ANLS\n"
    "        v_refused.append(False)\n"
    "\n"
    "        if (i + 1) % 10 == 0:\n"
    "            print(f'  Vector RAG [{i+1}/{len(pilot_questions)}]')\n"
    "\n"
    "    v_metrics = compute_all_metrics(v_preds, v_golds,\n"
    "                                    [True] * len(v_preds), v_refused)\n"
    "    vector_results = {\n"
    "        'system': 'Flat-vector RAG', 'n_questions': len(pilot_questions),\n"
    "        'metrics': v_metrics, 'predictions': v_preds, 'golds': v_golds,\n"
    "    }\n"
    "    vector_out_path.write_text(json.dumps(vector_results, indent=2), encoding='utf-8')\n"
    "    print(f'Flat-vector RAG: ANLS={v_metrics[\"anls\"]:.3f} '\n"
    "          f'F1={v_metrics[\"f1\"]:.3f} Acc={v_metrics[\"accuracy\"]:.3f}')\n"
    "    print(f'Saved: {vector_out_path}')"
))

# ── Phase 9 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 9 -- GraMM-RAG Full Evaluation (3 Seeds)\n"
    "\n"
    "Full pipeline: **route -> retrieve (HGT/FAISS) -> self-heal -> generate -> score**\n"
    "\n"
    "Gold answers: `valid_answers` list (ANLS computed as max over all valid answers).  \n"
    "Results saved per seed to `results/gramm_mpdocvqa_pilot_s{seed}.json`."
))

cells.append(code(
    "from src.retrieval.router import QueryRouter\n"
    "from src.retrieval.self_healing import SelfHealingRetriever\n"
    "\n"
    "hgt_model_eval = DocumentHGT(metadata=METADATA).to(DEVICE)\n"
    "if hgt_save_path.exists():\n"
    "    hgt_model_eval.load_state_dict(\n"
    "        torch.load(hgt_save_path, map_location=DEVICE, weights_only=False))\n"
    "    print(f'HGT loaded: {hgt_save_path}')\n"
    "else:\n"
    "    print('Warning: HGT weights not found -- using random init')\n"
    "hgt_model_eval.eval()\n"
    "\n"
    "router = QueryRouter(\n"
    "    model_dir=str(router_save_dir) if router_save_dir.exists() else None,\n"
    "    device=DEVICE,\n"
    ")\n"
    "print(f'Router: {\"DeBERTa\" if router.model else \"heuristic fallback\"}')\n"
    "\n"
    "reward_fn = RewardFunction(\n"
    "    params_path=str(reward_save) if reward_save.exists() else None)\n"
    "\n"
    "retriever = SelfHealingRetriever(\n"
    "    hgt_model=hgt_model_eval, reward_fn=reward_fn,\n"
    "    top_k=10, expansion_k=5, max_rounds=2,\n"
    ")\n"
    "vlm_eval = VLMClient(provider='together')\n"
    "print('All GraMM-RAG components loaded.')"
))

cells.append(code(
    "def run_gramm_rag_mpdocvqa(questions, seed):\n"
    "    random.seed(seed)\n"
    "    torch.manual_seed(seed)\n"
    "    predictions, golds, refused_flags, reward_scores = [], [], [], []\n"
    "\n"
    "    for i, item in enumerate(questions):\n"
    "        question   = item['question']\n"
    "        gold_list  = item['answers']   # list of valid answers\n"
    "        doc_id     = item['doc_id']\n"
    "\n"
    "        graph  = load_graph(str(GRAPH_DIR), doc_id)\n"
    "        pf     = PARSED_DIR / f'{doc_id}.json'\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8')) if pf.exists() else None\n"
    "        route  = router.route(question)\n"
    "\n"
    "        text_pt   = EMB_DIR / f'{doc_id}_text.pt'\n"
    "        query_emb = (torch.load(text_pt, weights_only=True).mean(0)\n"
    "                     if text_pt.exists() else torch.zeros(256))\n"
    "\n"
    "        if graph and parsed and route in ('GRAPH', 'HYBRID'):\n"
    "            result = retriever.retrieve(query_emb, graph, parsed, [])\n"
    "        else:\n"
    "            vi    = faiss_indices.get(doc_id)\n"
    "            nodes = vi.search(query_emb, top_k=10) if vi and vi.index else []\n"
    "            result = {'nodes': nodes, 'reward': 0.5, 'refused': False,\n"
    "                      'rounds': 0, 'reward_detail': {}}\n"
    "\n"
    "        prompt = build_prompt(\n"
    "            question, result['nodes'],\n"
    "            parsed or {'elements': []},\n"
    "            result['reward_detail'], result['refused'],\n"
    "            benchmark='mpdocvqa',\n"
    "        )\n"
    "        answer = vlm_eval.generate(prompt, temperature=0.0, max_tokens=128)\n"
    "\n"
    "        predictions.append(answer)\n"
    "        golds.append(gold_list)\n"
    "        refused_flags.append(result['refused'])\n"
    "        reward_scores.append(result['reward'])\n"
    "\n"
    "        if (i + 1) % 10 == 0:\n"
    "            print(f'  [{i+1}/{len(questions)}] route={route} '\n"
    "                  f'R={result[\"reward\"]:.2f} refused={result[\"refused\"]}')\n"
    "\n"
    "    # MP-DocVQA: all questions are answerable\n"
    "    is_answerable = [True] * len(predictions)\n"
    "    metrics = compute_all_metrics(predictions, golds, is_answerable, refused_flags)\n"
    "    return {\n"
    "        'n_questions':   len(questions),\n"
    "        'metrics':       metrics,\n"
    "        'predictions':   predictions,\n"
    "        'golds':         golds,\n"
    "        'reward_scores': reward_scores,\n"
    "        'refused_flags': refused_flags,\n"
    "    }\n"
    "\n"
    "print('run_gramm_rag_mpdocvqa() defined.')"
))

cells.append(code(
    "gramm_results = {}\n"
    "\n"
    "for seed in [42, 123, 456]:\n"
    "    out_path = RESULTS_DIR / f'gramm_mpdocvqa_pilot_s{seed}.json'\n"
    "    if out_path.exists():\n"
    "        print(f'Seed {seed}: results exist at {out_path}')\n"
    "        gramm_results[seed] = json.loads(out_path.read_text())\n"
    "        continue\n"
    "    print(f'\\n=== GraMM-RAG / seed={seed} ===')\n"
    "    res = run_gramm_rag_mpdocvqa(pilot_questions, seed=seed)\n"
    "    gramm_results[seed] = res\n"
    "    out_path.write_text(json.dumps(res, indent=2), encoding='utf-8')\n"
    "    m = res['metrics']\n"
    "    print(f'  ANLS={m[\"anls\"]:.3f}  F1={m[\"f1\"]:.3f}  Acc={m[\"accuracy\"]:.3f}  '\n"
    "          f'Refused={sum(res[\"refused_flags\"])}/{res[\"n_questions\"]}')\n"
    "\n"
    "print('\\nAll seeds complete.')"
))

# ── Phase 10 ──────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 10 -- Results Comparison Table\n"
    "\n"
    "Aggregate GraMM-RAG results across 3 seeds and compare against the flat-vector RAG baseline.  \n"
    "Primary metric: ANLS (DocVQA standard)."
))

cells.append(code(
    "import pandas as pd\n"
    "\n"
    "rows = []\n"
    "\n"
    "if vector_out_path.exists():\n"
    "    vr = json.loads(vector_out_path.read_text())\n"
    "    m  = vr['metrics']\n"
    "    rows.append({\n"
    "        'System': 'Flat-vector RAG',\n"
    "        'N': vr['n_questions'],\n"
    "        'ANLS': f\"{m['anls']:.3f}\",\n"
    "        'F1':   f\"{m['f1']:.3f}\",\n"
    "        'Accuracy': f\"{m['accuracy']:.3f}\",\n"
    "        'Refused': 0, 'Seed': '-',\n"
    "    })\n"
    "\n"
    "anls_vals, f1_vals, acc_vals = [], [], []\n"
    "for seed, res in sorted(gramm_results.items()):\n"
    "    m = res['metrics']\n"
    "    rows.append({\n"
    "        'System': 'GraMM-RAG',\n"
    "        'N': res['n_questions'],\n"
    "        'ANLS': f\"{m['anls']:.3f}\",\n"
    "        'F1':   f\"{m['f1']:.3f}\",\n"
    "        'Accuracy': f\"{m['accuracy']:.3f}\",\n"
    "        'Refused': sum(res['refused_flags']),\n"
    "        'Seed': seed,\n"
    "    })\n"
    "    anls_vals.append(m['anls'])\n"
    "    f1_vals.append(m['f1'])\n"
    "    acc_vals.append(m['accuracy'])\n"
    "\n"
    "if anls_vals:\n"
    "    rows.append({\n"
    "        'System': 'GraMM-RAG (mean+-std)',\n"
    "        'N': len(pilot_questions),\n"
    "        'ANLS': f\"{np.mean(anls_vals):.3f}+-{np.std(anls_vals):.3f}\",\n"
    "        'F1':   f\"{np.mean(f1_vals):.3f}+-{np.std(f1_vals):.3f}\",\n"
    "        'Accuracy': f\"{np.mean(acc_vals):.3f}+-{np.std(acc_vals):.3f}\",\n"
    "        'Refused': '-', 'Seed': 'mean',\n"
    "    })\n"
    "\n"
    "if rows:\n"
    "    df = pd.DataFrame(rows)\n"
    "    print('=== GraMM-RAG vs Flat-Vector RAG on MP-DocVQA ===')\n"
    "    print(f'Pilot: N_PILOT={N_PILOT} questions, Seed={SEED}')\n"
    "    print()\n"
    "    print(df.to_string(index=False))\n"
    "else:\n"
    "    print('No results yet. Run Phases 8-9 first.')"
))

cells.append(code(
    "summary = {\n"
    "    'N_PILOT': N_PILOT, 'SEED': SEED, 'benchmark': 'MP-DocVQA',\n"
    "    'flat_vector_rag': json.loads(vector_out_path.read_text())['metrics']\n"
    "        if vector_out_path.exists() else None,\n"
    "    'gramm_rag': {str(s): r['metrics'] for s, r in gramm_results.items()},\n"
    "}\n"
    "(RESULTS_DIR / 'summary_mpdocvqa_pilot.json').write_text(\n"
    "    json.dumps(summary, indent=2), encoding='utf-8')\n"
    "\n"
    "print('All results saved to results/')\n"
    "print()\n"
    "print('To extend to the FULL 5,187-question run:')\n"
    "print('  1. Set N_PILOT = None  in Phase 0 (Cell 1)')\n"
    "print('  2. Re-run all cells')\n"
    "print('  3. Estimated API cost: ~$5-10 (Llama-3.3-70B-Turbo x 3 seeds x 5,087 remaining Qs)')"
))

# ── Build notebook JSON ───────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbformat": 4,
            "version": "3.10.0"
        }
    },
    "cells": cells,
}

out = pathlib.Path(__file__).parent / "mpdocvqa_e2e.ipynb"
out.write_text(json.dumps(notebook, indent=1, ensure_ascii=False), encoding="utf-8")
print(f"Notebook written: {out}")
print(f"Total cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='markdown')} md + "
      f"{sum(1 for c in cells if c['cell_type']=='code')} code)")
